django3/django3/urls.py
from django.contrib import admin
from django.urls import path, include
#为了插入图片
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))#应用名
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

django3/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('list/', views.goods_list, name='list'),
    path('detail/', views.detail, name='detail'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('place_order/', views.placeorder, name='place_order'),
    path('site/', views.site, name='site'),
    path('shanchu/', views.shanchu, name='shanchu'),
    path('message/', views.message, name='message'),
    path('create_order/', views.create_order, name='create_order'),
    path('aaa/', views.aaa, name='aaa'),
    path('dell/', views.dell, name='dell'),
    path('order/', views.order, name='order'),
    path('log_off/', views.log_off, name='log_off'),
]

django3/shop/models.py
from django.db import models
from django.core import validators
import datetime


class Shop(models.Model):
    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
    username = models.CharField('用户名', unique=True, max_length=30,
                                validators=[validators.MinLengthValidator(
                                    limit_value=6, message='请输入6到20位用户名')])
    password = models.CharField('密码', max_length=32)
    address = models.CharField('地址', max_length=30, default='')
    email = models.EmailField('邮箱')


    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=['username'])


class Category(models.Model):
    """分类信息"""
    class Meta:
        verbose_name = '分类信息'
        verbose_name_plural = verbose_name
    name = models.CharField('名称', max_length=10)
    icon = models.ImageField('图片样式', max_length=20)


def upload_thumb(instance, filename):  #图片的上传，模型实例对象，文件名
    return '{0}_{1}.png'.format(
         instance.id, datetime.datetime.strftime(datetime.datetime.now(), '%Y%m%d%H%M%S')
     )


class Goods(models.Model):
    """商品信息"""
    class Meta:
        verbose_name = '商品信息'
        verbose_name_plural = verbose_name
    Category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField('名称', max_length=30)
    price = models.DecimalField('价格', max_digits=5, decimal_places=2)
    thumb = models.ImageField('主图', upload_to=upload_thumb, null=True, blank=True)
    brief = models.CharField('简介', max_length=100, default=0)
    unit = models.IntegerField('单位', default=5)
    intorduce = models.CharField('介绍', max_length=100, default=1)


class Cart(models.Model):
    """购物车"""
    user = models.OneToOneField(Shop, on_delete=models.CASCADE)
    goods = models.ManyToManyField(Goods, through='CartGoods', through_fields=('cart', 'goods'))


class CartGoods(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)
    number = models.SmallIntegerField(default=0)


class Site(models.Model):
    class Meta:
        verbose_name = '编辑地址'
        verbose_name_plural = verbose_name
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)   #外键是父表写在子表里
    addressee = models.CharField('收件人', max_length=30)
    amply = models.CharField('详细地址', max_length=100)
    zip = models.IntegerField('邮编')
    phone = models.CharField('手机', max_length=11)


class OrderInfo(models.Model):
    """订单信息"""
    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name
    user = models.ForeignKey(Shop, on_delete=models.CASCADE, verbose_name='用户')
    goods = models.ManyToManyField(Goods, through='OrderGoods', through_fields=('order_info', 'goods'), verbose_name='商品')
    pay_status = models.SmallIntegerField('支付状态', choices=[(0, '未付款'), (1, '付款中'), (2, '已付款')], default=0)
    shipping_status = models.SmallIntegerField('配送状态', choices=[(0, '未发货'), (1, '已发货'), (2, '已收货'), (3, '退货 ')], default=0)
    add_time = models.DateTimeField('创建时间', auto_now_add=True)


class OrderGoods(models.Model):
    """订单商品（订单和商品是多对多关系，该表是中间表）"""
    order_info = models.ForeignKey(OrderInfo, on_delete=models.CASCADE, verbose_name='订单ID')
    goods = models.ForeignKey(Goods, '商品ID')
    number = models.SmallIntegerField('数量')










# Create your models here.

django3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% load static %}
    <title> {% block title %}标题{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'reset.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="shortcut icon" href="{% static 'logo02.png' %}">
    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'slide.js' %}"></script>
    <script type="text/javascript" src="{% static 'list.js' %}"></script>
</head>
<body>

{% block topbar %}
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            <div class="login_btn fl" style="display: block">
{#                如果有用户登录，放这个用户名，否则登录或注册#}
                {% if user %}
                    {{ user }}
                    <span></span>
                    <a href="{% url 'log_off' %}">注销</a>
                {% else %}
                    <a href="{% url 'login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'register' %}">注册</a>
                {% endif %}
            </div>

            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'index' %}">首页</a>
                <span>|</span>
                <a href="{% url 'message' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'order' %}">我的订单</a>

            </div>
        </div>
    </div>
</div>


<div class="search_bar clearfix">
    <a href="{% url 'index' %}" class="logo fl">
        <img src="{% static 'logo02.png' %}"></a>
    <div class="search_con fl">
        <form action="{% url 'list' %}">
            <input type="text" class="input_text fl" name="q" value="word" id="q" placeholder="搜索商品">
            <input type="submit" class="input_btn fr" id="search" name="" value="搜索">
        </form>


    </div>
    <div class="guest_cart fr">
        <a href="{% url 'cart' %}" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">0</div>
    </div>
</div>

<div class="navbar_con">
    <div class="navbar">
        <h1 class="fl">全部商品分类</h1>
        <ul class="navlist fl">
            <li><a href="{% url 'index' %}">首页</a></li>
            {% for category in categories %}
                <li class="interval">|</li>
                <li><a href="{% url 'list' %}?category_id={{ category.id }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock topbar %}

{% block content %}
这是内容部分
{% endblock content %}

<div class="footer">
    <div class="foot_link">
        <a href="http://www.xiaozhican.top/shop/index/#">关于我们</a>
        <span>|</span>
        <a href="http://www.xiaozhican.top/shop/index/#">联系我们</a>
        <span>|</span>
        <a href="http://www.xiaozhican.top/shop/index/#">招聘人才</a>
        <span>|</span>
        <a href="http://www.xiaozhican.top/shop/index/#">友情链接</a>
    </div>
    <p>CopyRight All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>

django3/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}购物车{% endblock title %}

{% block content %}

    <div class="total_count">全部商品<em>{{ num }}</em>件</div>
    <ul class="cart_list_th clearfix">
        <li class="col01">商品名称</li>
        <li class="col02">商品单位</li>
        <li class="col03">商品价格</li>
        <li class="col04">数量</li>
        <li class="col05">小计</li>
        <li class="col06">操作</li>
    </ul>
    {% for id in cart %}
        <ul class="cart_list_td clearfix">
            <li class="col01"><input data-id={{ id.id }} class="select" type="checkbox" name="" checked></li>
            <li class="col02"><img src="{{ MEDIA_URL }}{{ id.goods.thumb }}"></li>
            <li class="col03">{{ id.goods.name }}<br><em>{{ id.goods.price }}元/500g</em></li>
            <li class="col04">500g</li>
            <li class="col05">{{ id.goods.price }}元</li>
            <li class="col06">
                <div class="num_add">
                    <a href="javascript:;" class="add fl">+</a>
                    <input type="text" class="num_show fl" value="{{ id.number }}">
                    <a href="javascript:;" class="minus fl">-</a>
                </div>
            </li>
            <li class="col07"></li>
            <li class="col08"><a href="{% url 'shanchu' %}?cart_goods_id={{ id.id }}">删除</a></li>
        </ul>
    {% endfor %}

    <ul class="settlements">
        <li class="col01"><input id="selectAll" type="checkbox" name="" checked=""></li>
        <li class="col02">全选</li>
        <li class="col03">合计(不含运费)：<span>¥</span><em id="total"></em><br>共计<b id="count">{{ num }}</b>件商品</li>
        <li class="col04"><a id="jiesuan" href="{% url 'place_order' %}">去结算</a></li>
    </ul>

    <script src="./js/jquery-1.12.4.min.js"></script>
    <script>
        $('.add').click(function () {            //点击事件，定位到add
            // 获取原来的数量
            var n = parseInt($(this).next('.num_show').val())
            // 给数量加1
            $(this).next('.num_show').val(n + 1)
            $('.num_show').change()
            // // 获取商品单价
            // price = parseFloat($(this).parent().parent().prev().html()) * 100
            // // 计算小计
            // sum = price * (n+1)
            // // 获取小计的元素并赋值
            {#$(this).parent().parent().next().text(sum/100 + '元')#}
        })
        $('.minus').click(function () {               //定位到.minus,点击减号
            var n = parseInt($(this).prev('.num_show').val())           //所得值转化为整型
            if (n > 1) {                                                  //大于零可以减一
                $(this).prev('.num_show').val(n - 1)
                $('.num_show').change()
                // // 获取商品单价
                // price = parseFloat($(this).parent().parent().prev().html()) * 100
                // // 计算小计
                // sum = price * (n-1)
                // // 获取小计的元素并赋值
                // $(this).parent().parent().next().text(sum/100 + '元')
            }
        })
        $('.num_show').change(function () {
            // 获取商品单价
            price = parseFloat($(this).parent().parent().prev().html()) * 100      //价格是浮点数，防止出现一整串小数，乘一百
            // 计算小计
            sum = price * $(this).val()
            // 获取小计的元素并赋值
            $(this).parent().parent().next().text((sum / 100).toFixed(2) + '元')     //保留两位小数

            // 计算总价
            var total = 0
            $('.col07').each(function (i, el) {             //点位到col07,each循环,i是参数，el是元素
                if ($(this).parents('ul').find('.select').get(0).checked) {
                    total += parseFloat($(el).text()) * 100
                }
            })
            $('#total').text((total / 100).toFixed(2))
        })

        // 选择框改变，处理价格和数量计算
        $('.select').change(function () {
            n = parseInt($('#count').text())        //选择商品种类，计算个数
            if (this.checked) {                         //checked两个属性，True或False
                $('#count').text(n + 1)
            } else {
                if (n > 0) {
                    $('#count').text(n - 1)
                }
            }
            $('.num_show').change()
        })
        // 点击全选，计算价格和数量
        $('#selectAll').change(function () {
            checked = this.checked
            $('.select').each(function (i, el) {
                el.checked = checked
            })
            $('.select').change()
        })
    $('.num_show').change()
    </script>

{#去结算    #}
    <script>
        $('#jiesuan').click(function () {
            cartgoods = []
            $('.select:checked').each(function (i, el) {
                num = $(el).parents('ul').find('.num_show').val()
                id = $(el).attr('data-id')
                cartgoods.push({"num": num, "cartgoods_id": id})
            })
            console.log(cartgoods)
            $(this).attr('href', '{% url "place_order" %}?data=' + JSON.stringify(cartgoods))
        })
    </script>
{% endblock content %}

django3/templates/detail.html
{% extends 'base.html' %}

{% block title %}{{ goods.name }}{% endblock title %}

{% block content %}
    {% csrf_token %}
    {#	<div class="navbar_con">#}
    {#		<div class="navbar clearfix">#}
    {#			<div class="subnav_con fl">#}
    {#				<h1>全部商品分类</h1>	#}
    {#				<span></span>			#}
    {#				<ul class="subnav">#}
    {#					<li><a href="#" class="fruit">新鲜水果</a></li>#}
    {#					<li><a href="#" class="seafood">海鲜水产</a></li>#}
    {#					<li><a href="#" class="meet">猪牛羊肉</a></li>#}
    {#					<li><a href="#" class="egg">禽类蛋品</a></li>#}
    {#					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>#}
    {#					<li><a href="#" class="ice">速冻食品</a></li>#}
    {#				</ul>#}
    {#			</div>#}
    {#			<ul class="navlist fl">#}
    {#				<li><a href="">首页</a></li>#}
    {#				<li class="interval">|</li>#}
    {#				<li><a href="">手机生鲜</a></li>#}
    {#				<li class="interval">|</li>#}
    {#				<li><a href="">抽奖</a></li>#}
    {#			</ul>#}
    {#		</div>#}
    {#	</div>#}

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">新鲜水果</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ MEDIA_URL }}{{ goods.thumb }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ goods.name }}</h3>
            <p>{{ goods.brief }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em id="pr">{{ goods.price }}</em></span>
                <span class="show_unit">单  位：{{ goods.unit }}g</span>
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input id="goods_num" type="text" class="num_show fl" value="1">
                    <a href="javascript:;" class="add fr" id="add_num">+</a>
                    <a href="javascript:;" class="minus fr" id="minus_num">-</a>
                </div>
            </div>
            <div class="total">总价：<em id="total">{{ goods.price }}</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    <li>
                        <a href="#"><img src="images/goods/goods001.jpg"></a>
                        <h4><a href="#">进口柠檬</a></h4>
                        <div class="prize">￥3.90</div>
                    </li>
                    <li>
                        <a href="#"><img src="images/goods/goods002.jpg"></a>
                        <h4><a href="#">玫瑰香葡萄</a></h4>
                        <div class="prize">￥16.80</div>
                    </li>
                </ul>
            </div>
        </div>


        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>
            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ goods.intorduce }}
                    </dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="add_jump"></div>
    <script type="text/javascript">

        {# 数量的加减操作 #}
        $('#add_num').click(function () {
            {# jq的val()等同于js的 value 属性 #}
            $('#goods_num').val(parseInt($('#goods_num').val()) + 1)

            num = $('#goods_num').val()
            parseInt(num)
            $('#total').html($('#pr').html() * parseInt(num) + '元') //总价#}
        })

        $('#minus_num').click(function () {
            {# jq的val()等同于js的 value 属性 #}
            if ($('#goods_num').val() > 0) {
                $('#goods_num').val(parseInt($('#goods_num').val()) - 1)
            }
            num = $('#goods_num').val()
                parseInt(num)
                $('#total').html($('#pr').html() * parseInt(num) + '元') //总价
        })
        {#$('#total').html(parseInt($('#goods_num').val()) *  $('#pr').html() + '元')#}
        {#num=$('#goods_num').val()#}
        {#parseInt(num)#}
        {#$('#total').html($('#pr').html()* parseInt(num))#}

        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
        $('#add_cart').click(function () {
            $(".add_jump").stop().animate({
                    'left': $to_y + 7,
                    'top': $to_x + 7
                },
                "fast", function () {
                    $(".add_jump").fadeOut('fast');

                });


            {# 异步请求加入购物车 #}
            $.ajax({
                url: "{% url 'add_to_cart' %}",
                type: 'POST',
                {#将CSRF-Token返回服务端#}
                headers: {
                    'X-CSRFTOKEN': $.cookie('csrftoken')
                },
                data: {
                    goods_id: {{ goods.id }},
                    number: $('#goods_num').val()
                },
                success: function (res) {
                    $('#show_count').html(res);
                }
            })
        })
    </script>
{% endblock content %}

django3/templates/index.html
<!-- saved from url=(0037)http://www.xiaozhican.top/shop/index/ -->
{#<html>#}
{#<head>#}
{#    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">#}
{#    {% load static %}#}
{#    <title> 天天生鲜首页</title>#}
{#    <link rel="stylesheet" href="{% static 'reset.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'main.css' %}">#}
{#    <link rel="shortcut icon" href="{% static 'logo02.png' %}">#}
{#    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'jquery-ui.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'slide.js' %}"></script>#}
{#</head>#}
{#<body>#}
{##}
{#<div class="header_con">#}
{#    <div class="header">#}
{#        <div class="welcome fl">欢迎来到天天生鲜!</div>#}
{#        <div class="fr">#}
{#            <div class="login_btn fl" style="display: block">#}
{#                {% if user %}#}
{#                    {{ user }}#}
{#                {% else %}#}
{#                    <a href="{% url 'login' %}">登录</a>#}
{#                    <span>|</span>#}
{#                    <a href="{% url 'register' %}">注册</a>#}
{#                {% endif %}#}
{#            </div>#}
{##}
{#            <div class="user_link fl">#}
{#                <span>|</span>#}
{#                <a href="http://www.xiaozhican.top/shop/index/">首页</a>#}
{#                <span>|</span>#}
{#                <a href="http://www.xiaozhican.top/account/user_center_info/">用户中心</a>#}
{#                <span>|</span>#}
{#                <a href="http://www.xiaozhican.top/shop_cart/shop_cart/">我的购物车</a>#}
{#                <span>|</span>#}
{#                <a href="http://www.xiaozhican.top/account/user_center_order/">我的订单</a>#}
{##}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{##}
{##}
{#<div class="search_bar clearfix">#}
{#    <a href="http://www.xiaozhican.top/shop/index/" class="logo fl">#}
{#        <img src="{% static 'logo02.png' %}"></a>#}
{#    <div class="search_con fl">#}
{#        <form action="http://www.xiaozhican.top/search/">#}
{#            <input type="text" class="input_text fl" name="q" value="" id="q" placeholder="搜索商品">#}
{#            <input type="submit" class="input_btn fr" id="search" name="" value="搜索">#}
{#        </form>#}
{##}
{##}
{#    </div>#}
{#    <div class="guest_cart fr">#}
{#        <a href="http://www.xiaozhican.top/shop_cart/shop_cart/" class="cart_name fl">我的购物车</a>#}
{#        <div class="goods_count fl" id="show_count">0</div>#}
{#    </div>#}
{#</div>#}
{##}
{#<div class="navbar_con">#}
{#    <div class="navbar">#}
{#        <h1 class="fl">全部商品分类</h1>#}
{#        <ul class="navlist fl">#}
{#            <li><a href="http://www.xiaozhican.top/shop/index/">首页</a></li>#}
{#            {% for category in categories %}#}
{#                <li class="interval">|</li>#}
{#                <li><a href="http://www.xiaozhican.top/shop/categorys/5/">{{ category.name }}</a></li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    </div>#}
{#</div>#}


{% extends 'base.html' %}

{% load static %}

{% block title %}首页{% endblock title %}

{% block content %}
<div class="center_con clearfix">
    <ul class="subnav fl">
        {% for category in categories %}
            <li><a href="{% url 'list' %}?category_id={{ category.id }}" class="{{ category.icon }}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>

    <div class="slide fl">
        <ul class="slide_pics">
            <li style="left: -760px;"><img src="{% static 'slide.jpg' %}" alt="幻灯片"></li>
            <li style="left: 0px;"><img src="{% static 'slide02.jpg' %}" alt="幻灯片"></li>
            <li style="left: 760px;"><img src="{% static 'slide03.jpg' %}" alt="幻灯片"></li>
            <li style="left: 760px;"><img src="{% static 'slide04.jpg' %}" alt="幻灯片"></li>
        </ul>
        <div class="prev"></div>
        <div class="next"></div>
        <ul class="points">
        </ul>
    </div>
    <div class="adv fl">
        <a href="http://www.xiaozhican.top/shop/index/#"><img src="{% static 'adv01.jpg' %}"></a>
        <a href="http://www.xiaozhican.top/shop/index/#"><img src="{% static 'adv02.jpg' %}"></a>
    </div>
</div>

{% for category in categories %}
    <div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model01">{{ category.name }}</h3>
        <a href="http://www.xiaozhihcan.top/shop/categorys/1/" class="goods_more fr" id="fruit_more">查看更多 &gt;</a>
    </div>
    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="{{ MEDIA_URL }}{{ category.icon }}"></div>
        <ul class="goods_list fl">
{#        切片，只显示四页#}
            {% for goods in category.goods_set.all|slice:':4' %}
                <li>
                    <h4><a href="{% url 'detail' %}?goods_id={{ goods.id }}">{{ goods.name }}</a></h4>
                    <a href="{% url 'detail' %}?goods_id={{ goods.id }}">
                        <img src="{{ MEDIA_URL }}{{ goods.thumb }}">
                    </a>
                    <div class="prize">¥ {{ goods.price }}</div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endfor %}
{% endblock content %}

django3/templates/text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'text' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">提交</button>

</form>
</body>
</html>

django3/templates/user_center_order.html
{% extends 'base.html' %}

{% load static %}

{% block title %}全部订单{% endblock title %}

{% block content %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'message' %}">· 个人信息</a></li>
                <li><a href="{% url 'order' %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'site' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            {% for items in page.object_list %}
                <h3 class="common_title2">全部订单</h3>
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ items.add_time }}</li>
                    <li class="col02">订单号：56872934</li>
                    <li class="col02 stress">{{ items.get_pay_status_display }}</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">

                            <ul class="order_goods_list clearfix">
                                {% for id in items.ordergoods_set.all %}

                                    <li class="col01"><img src="{{ MEDIA_URL }}{{ id.goods.thumb }}"></li>
                                    <li class="col02">{{ id.goods.name }}<em class="price">{{ id.goods.price }}元/500g</em></li>
                                    <li class="col03">{{ id.number }}</li>
                                    <li class="col04">元</li>

                                {% endfor %}
                            </ul>
                        </td>
                        <td width="15%" id="total">元</td>
                        <td width="15%">待付款</td>
                        <td width="15%"><a href="{% url 'order' %}" class="oper_btn">去付款</a></td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}
            <div class="pagenation">

                {% for page in page.paginator.page_range %}
                    <a href="{% url 'order' %}?num={{ page }}"
                       class="active" style="background-color: #1b6d85">{{ page }}</a>
                {% endfor %}

            </div>
        </div>
    </div>

    <script>
    $(document).ready(function () {
        $('.price').each(function (i,el){
            var price = parseFloat($(el).html())
            var number = $(el).parents('li').next().html()
            $(el).parents('li').next().next().html((price*number).toFixed(2)+"元")
        })
        var total = 0
        $('.col04').each(function (i,el) {
            total += parseFloat($(el).html())*100
            $('#total').html((total/100).toFixed(2)+"元")
        })
    })
    </script>

{% endblock content %}